export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';

export const ENABLE_NOTIFICATIONS = 'ENABLE_NOTIFICATIONS';

export const DISABLE_NOTIFICATIONS = 'DISABLE_NOTIFICATIONS';

export const SET_DARKMODE = 'SET_DARKMODE';

export const SET_LIGHTMODE = 'SET_LIGHTMODE';

export const CHANGE_THEME = 'CHANGE_THEME';

export const REMOVE_ADS = 'REMOVE_ADS';

export const UPGRADE_TO_PREMIUM = 'UPGRADE_TO_PREMIUM';
