const products = [
  {
    name: 'Pencil',
    description: 'Lorem ipsum dolor sit amet',
    price: 99,
    inCart: false,
    amount: 0,
    id: 1,
  },
  {
    name: 'Pen',
    description: 'Lorem ipsum dolor sit amet',
    price: 59,
    inCart: false,
    amount: 0,
    id: 2,
  },
  {
    name: 'Ruler',
    description: 'Lorem ipsum dolor sit amet',
    price: 349,
    inCart: false,
    amount: 0,
    id: 3,
  },
  {
    name: 'Eraser',
    description: 'Lorem ipsum dolor sit amet',
    price: 49,
    inCart: false,
    amount: 0,
    id: 4,
  },
  {
    name: 'Book',
    description: 'Lorem ipsum dolor sit amet',
    price: 49,
    inCart: false,
    amount: 0,
    id: 5,
  },
  {
    name: 'Mathematical Set',
    description: 'Lorem ipsum dolor sit amet',
    price: 149,
    inCart: false,
    amount: 0,
    id: 6,
  },
  {
    name: 'Sharpener',
    description: 'Lorem ipsum dolor sit amet',
    price: 99,
    inCart: false,
    amount: 0,
    id: 7,
  },
  {
    name: 'Calculator',
    description: 'Lorem ipsum dolor sit amet',
    price: 59,
    inCart: false,
    amount: 0,
    id: 8,
  },
  {
    name: 'Desk Organizer',
    description: 'Lorem ipsum dolor sit amet',
    price: 349,
    inCart: false,
    amount: 0,
    id: 9,
  },
  {
    name: 'Clip Board',
    description: 'Lorem ipsum dolor sit amet',
    price: 49,
    inCart: false,
    amount: 0,
    id: 10,
  },
  {
    name: 'Scissor',
    description: 'Lorem ipsum dolor sit amet',
    price: 49,
    inCart: false,
    amount: 0,
    id: 11,
  },
  {
    name: 'Glue',
    description: 'Lorem ipsum dolor sit amet',
    price: 149,
    inCart: false,
    amount: 0,
    id: 12,
  },
  {
    name: 'Tapes and Adhesives',
    description: 'Lorem ipsum dolor sit amet',
    price: 99,
    inCart: false,
    amount: 0,
    id: 13,
  },
  {
    name: 'ID Holder and Name Badge',
    description: 'Lorem ipsum dolor sit amet',
    price: 59,
    inCart: false,
    amount: 0,
    id: 14,
  },
  {
    name: 'Book Rack',
    description: 'Lorem ipsum dolor sit amet',
    price: 349,
    inCart: false,
    amount: 0,
    id: 15,
  },
];

export default products;
